version: "3"
services:

  database:
    # image: mariadb:10.5.4
    build: ./d8-database-inside
    container_name: d8_db
    environment:
      - MYSQL_ROOT_PASSWORD=drupal8
      - MYSQL_USER=drupal8
      - MYSQL_PASSWORD=drupal8
      - MYSQL_DATABASE=drupal8
    ports:
      - "3306:3306"
      
  php:
    # image: drupal:8.9.2-fpm
    build:
      context: ./d8-codebase-inside/
      dockerfile: Dockerfile-d8
    container_name: d8_php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
     
  nginx:
    # image: nginx:1.19.1
    build:
      context: ./d8-codebase-inside
      dockerfile: Dockerfile-nginx
    container_name: d8_nginx
    ports:
      - "8080:80"
      - "8443:443" 
    links:
     - php
     - database
    volumes:
       - ./src:/var/www/html
   
