version: "3"
services:

  database:
    image: mariadb:10.5.4
    build: ./d8-database-inside
    environment:
      - MYSQL_ROOT_PASSWORD=drupal8
      - MYSQL_USER=drupal8
      - MYSQL_PASSWORD=drupal8
      - MYSQL_DATABASE=drupal8
     ports:
      - "3306:3306"
    # volumes:
      # - "../db:/var/lib/mysql"
      
  php:
    image: php:7.4.8-fpm-buster
    build: ./d8-codebase-inside
    container_name: d8_php
    ports:
      - "9000:9000"
    # volumes:
      # - ../src:/var/www/html
      
   web:
    image: nginx:1.19.1
    build: ./d8-nginx-conf-codebase-inside
    ports:
      - "80:80"
    links:
     - php
     - database
    # volumes:
      # - ./server.conf:/etc/nginx/nginx.conf:ro
      # - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      # - ../src:/var/www/html     
      
  
