version: "3.6"
services:

  database:
    # image: mariadb:10.5.4
    build: ./d8-database-inside
    container_name: d8_db
    environment:
      - MYSQL_ROOT_PASSWORD=drupal8
      - MYSQL_USER=drupal8
      - MYSQL_PASSWORD=drupal8
      - MYSQL_DATABASE=drupal8
    ports:
      - "3306:3306"
    # volumes:
      # - "../db:/var/lib/mysql"
      
  php:
    # image: php:7.4.8-fpm-buster
    build:
      context: .
      dockerfile: ./d8-codebase-inside/Dockerfile-d8
    container_name: d8_php
    ports:
      - "9000:9000"
    # volumes:
      # - ../src:/var/www/html
      
  nginx:
    # image: nginx:1.19.1
    build:
      context: .
      dockerfile: ./d8-codebase-inside/Dockerfile-nginx
    container_name: d8_nginx
    ports:
      - "8080:80"
    links:
     - php
     - database
    # volumes:
      # - ./server.conf:/etc/nginx/nginx.conf:ro
      # - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      # - ../src:/var/www/html     
   
