FROM drupal:8.9.2-fpm

RUN docker-php-ext-install bcmath
	
# Install Composer, Drush
RUN curl -o /tmp/composer-setup.php https://getcomposer.org/installer \
  && curl -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
  && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
  && php /tmp/composer-setup.php --filename composer --install-dir /usr/local/bin \
  && curl -Lo /usr/local/bin/drush https://github.com/drush-ops/drush/releases/download/8.3.5/drush.phar \
  && chmod +x /usr/local/bin/drush \
  && /usr/local/bin/drush --version
  
COPY ./src/   /var/www/html
COPY ./settings.local.php   /var/www/html/web/sites/default/settings.local.php
COPY ./files   /var/www/html/web/sites/default/files

ENV COMPOSER_ALLOW_SUPERUSER 1

RUN cd /var/www/html; composer install
